# Generated by Django 2.1.7 on 2019-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_bare',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_cisco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_dashed',
            field=models.TextField(null=True),
        ),
    ]
